# Generated by Django 4.1.6 on 2023-04-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.CharField(max_length=50)),
                ('finalizado', models.CharField(choices=[('Não assistido', 'Não assistido'), ('Assistido', 'Assistido')], default=False, max_length=50)),
                ('resenha', models.TextField(max_length=256)),
            ],
        ),
    ]
