# Generated by Django 4.1.6 on 2023-04-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meus_animes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='finalizado',
            new_name='status',
        ),
    ]
